### PR TITLE
update to elixir 0.11.3 for compiling

### PR DESCRIPTION
**Pull request by jimiray**
I couldn't get the tests to run correctly.  I'm not that good at Elixir yet, but was trying to use Atlas in a dynamo learning project.  

Do I need to create a specific database to run the tests?

### CODE REVIEW

**Comment by chrismccord** [comment]
I have this merged locally and I'm working through the other changes required to get things passing on 0.11. I just added a "Testing" section to the readme that includes the requirements for the test suite.

https://github.com/chrismccord/atlas/blob/master/README.md#testing

The app still fails to boot because of a couple 0.11 changes, but you can check out the `0.11-fix` branch that I'm working on which includes your fixes. Thanks!

**Comment by jimiray** [comment]
Thanks.  I'll pull down that branch and try to get the tests running locally also.

**Comment by chrismccord** [comment]
It turns out there is an issue in Elixir 0.11.3 that was not allowing `Record` to be namespaces under models. This has been fixed on Elixir master, so you'll also need to grab that.

**Comment by chrismccord** [comment]
Tests are (nearly) passing on master now with 1 failure. There were quite a few 0.11 changes that had to be updated but I think we have just about everything fixed. There are still issues with preloading records, but I hope to have that fixed soon. Give the test suite a shot with Elixir master and let me know if you're up and running. Thanks!

**Pull request merged**
